[theme]
base="light"
secondaryBackgroundColor="#d3d3da"
textColor="#000000"

#[theme]
#primaryColor = "#e74c3c"
#backgroundColor = "#2c3e50"
#secondaryBackgroundColor = "#34495e"
#textColor = "#ecf0f1"
#font = "monospace"
